### ISSUE TITLE
Not so much an issue ...

### ISSUE THREAD

**Issue by ghost** [dingbat/nsrails#14]
Hey,

When I found NSRails I was really intrigued. I'm a seasoned Objective-C developer and I'm working on a project that requires a Rails back-end and thought I'd found a framework that may well help out. That was until I started seeing things like `NSRMap(*)` and `NSRUseModelName(@"subscriber")`.

You make heavy use of compiler macros throughout the framework, and I can perhaps understand why this would be if you're a Ruby developer coming to Objective-C (_after all, magic is inherent to Ruby_) but for an Objective-C developer this isn't a standard convention. By using macros in this way, the developer relinquishes control. Whilst it may look simpler (_and  prettier_) on the surface, debugging any issues would be a nightmare and behaviour cannot be overridden.

What I found frustrating was that in the Ruby version where you've been unable to perform similar _magic_, you've actually adhered to the Objective-C convention of providing a base class with default behaviour and then allowing developers to override the methods to customise the behaviour. For example, the way you handle `NSRUseModelName` in Ruby.

I know other things have already been brought to your attention, such as using the **NS** prefix, but the conventions and standards _are_ there for a reason. If you haven't done so already, it may be worthwhile reading through [Open Source Code](http://mattgemmell.com/2011/12/19/open-source-code/) by Matt Gemmell (_specifically the 'Speak the language' paragraph_) and [API Design](http://mattgemmell.com/2012/05/24/api-design/) by Matt Gemmell (_specifically Rule 1_).

For instance, you already have this in Ruby ...

``` ruby
class User < NSRRemoteObject
  def self.NSRUseModelName
    "subscriber"
  end

  #optional method to define plural
  def self.NSRUsePluralName
    "subscriberz"
  end
end
```

So why not have the equivalent in Objective-C ...

``` objective-c
@implementation User

 - (NSString *)modelName
{
    return @"subscriber";
}

 - (NSString *)pluralizedModelName
{
    return @"subscriberz";
}

@end
```

Not only will you be staying true to the language and abiding by the conventions, you'll also have consistency across the two languages (_where it's appropriate_).

It'd be great to get your thoughts on this. I did try to contact you on Twitter but I don't think you use your account that often.

Regards,

-Mic

**Comment by dingbat** [comment]
Hey Mic

Thanks a lot for your feedback.

To start off, I actually am primarily an Objective-C developer and do understand the importance of convention. I just love trying to make nice-looking APIs :) I know the convention to use macros is not super-standard, but I did think it through before making this decision and believe their use in NSRails is acceptable.

I understand the dangers of using macros, as they are tough to debug, but take a look at their implementations in NSRMacros.h. Each macro is literally a shorthand for a method definition - _nothing else_:

```
#define _NSR_Name2(name,plural) \
    + (NSString*) NSRUseModelName { return (name); } \
    + (NSString*) NSRUsePluralName { return (plural); }
```

All the logic of processing the name, etc, is done in solid code in NSRRemoteObject.

This:

``` objc
@implementation User
NSRUseModelName(@"subscriber", @"subscriberz");

@end
```

Actually expands to:

``` objc
@implementation User

+ (NSString *) NSRUseModelName
{
    return @"subscriber";
}

+ (NSString *) NSRUsePluralName
{
    return @"subscriberz";
}

@end
```

So, with a bit of tweaking, your code example above will actually work! Expanding them yourself will work exactly the same way. The same thing can be done with NSRMap:

``` objc
+ (NSString *) NSRMap
{
    return @"*";
}
```

This is why the magic doesn't port to Ruby that easily - they really are methods underneath it all :)

I guess I'll add this to the Wiki, as it could help others with the same irk.

Let me know if this resolves your conflicts.

Dan

**Comment by ghost** [comment]
Hey Dan,

Interesting! Thanks for the clarification.

Based on what you've stated, I must then ask _why_?

``` objective-c
@implementation User

NSRUseModelName(@"subscriber", @"subscriberz");

@end
```

Is this really a nice-looking API? It provides absolutely no context. _What are those two parameters? Why are there two? What do they do?_

Even if I were to simply override the methods the macro generates as you suggest, they're still not as clean nor as clear as they could be ...

``` objective-c
@implementation User

+ (NSString *) NSRUseModelName
{
    return @"subscriber";
}

+ (NSString *) NSRUsePluralName
{
    return @"subscriberz";
}

@end
```

versus

``` objective-c
@implementation User

 - (NSString *)modelName
{
    return @"subscriber";
}

 - (NSString *)pluralizedModelName
{
    return @"subscriberz";
}

@end
```

For me the latter is a far nicer looking API, and the method names provide clarity and intent as to what they do.

NSRails is a great concept, and I hope you don't take any of this criticism in a way other than which it's intended, constructive.

I may fork the project and flesh it out the way I've discussed here. It'd be more work than just dropping it in as-is, but I think it may be worth it in the long run.

Regards,

-Mic

**Comment by dingbat** [comment]
You've convinced me. You're right - that is cleaner. I'll also change `pluralizedModelName` to `controllerName`.
(I also want to note that these are _class_ methods - you made them instance in your example.)

However, I do want to keep NSRMap as a macro because right now the NSRMap callback function is expected to return a string (the macro simply returns the set of params passed in as a string), which could be confusing to a developer overriding it. I want to keep this string-based implementation, as changing it to be more of a callback would be a huge effort right now (and would be really tricky the amount of options NSRMap allows).

Also, NSRMap was originally intended to be almost like a NSRails-specific `@synthesize` - something that goes right along with all your property declarations, and I think I like it how it is. I hope that doesn't deter you from using NSRails!

Thanks for your input, again. I'm gonna keep the macros in for a bit but push for this in the documentation.

**Comment by ghost** [comment]
> Also, NSRMap was originally intended to be almost like a NSRails-specific @synthesize - something that goes right along with all your property declarations, and I think I like it how it is. I hope that doesn't deter you from using NSRails!

If _only_ we could add compiler directives at runtime, now that'd be cool!

Whilst I admire your approach, and your intention with NSRMap, I do still think it could be handled using a more standard approach without losing any of the flexibility it currently allows.

For instance, instead of passing a string which is then parsed under-the-hood to determine which flags you're setting on what properties, you could simply provide a lightweight configuration class (_nothing more than a bunch of properties_). The base model class would set up some sensible defaults, and then the developer could include an optional delegate method to fine tune the configuration (_which would be called for each property on the class_) ...

``` objective-c
- (NSRPropertyConfiguration *)willUseConfiguration:(NSRPropertyConfiguration *)config forProperty:(NSString *)property
{
    if ([property isEqualToString:@"user"]) {
        config.remoteProperty = @"person";
        config.association = @"people";
        config.propertyType = NSRPropertyTypeSendable;
        config.relationshipType = NSRRelationshipTypeHasMany;
        config.nested = YES;
    }
    return config;
}
```

Also, instead of providing a flag or property to use custom encoding/decoding and then a pair of methods for each property requiring it, you could simply implement two methods in the base model class which can then be overridden by the developer (_again these methods would be called for every property, each time the encoding/decoding needs to happen_) ...

Base model class implementations ...

``` objective-c
- (id)encodeProperty:(NSString *)property
{
    return [self valueForKey:property];
}

- (id)decodeProperty:(NSString *)property usingRemoteValue:(id)value
{
    return value;
}
```

An example of the methods being overridden to provide custom functionality in a subclass ...

``` objective-c
- (id)encodeValueForProperty:(NSString *)property
{
    if ([property isEqualToString:@"url"]) {
        // a property that needs encoding
        return [self.url absoluteString];
    }
    // if no encoding is required, just return the property as is
    return [self valueForKey:property];
}

- (id)decodeProperty:(NSString *)property usingRemoteValue:(id)value
{
    if ([property isEqualToString:@"url"]) {
        // a property that needs decoding
        return [NSURL URLWithString:(NSString *)value];
    }
    // if no decoding is required, just return the value
    return value;
}
```

Would love to get your thoughts on this.

Regards,

-Mic

_Disclaimer - this has all come straight out of my head, nothing has been tested and there may well be glaring issues or omissions. This is simply an idea on how things could look._ :)

**Comment by dingbat** [comment]
Hey Mic,

Thanks for the idea and examples.

I definitely considered this approach, but I would just like you to look all the code that you had to write, and then compare it to a one-line `NSRMap()`.

I believe that using the macro is much more developer-friendly. The less code the developer has to write, the less room there are for bugs. Of course, the tradeoff is flexibility, but NSRMap was designed with that in mind.

The example you gave was simple but you have to consider the amount of properties needing custom behavior on a large project. 

Having to do an if,

``` objc
if ([property isEqualToString:@"user"]) 
{
    config.remoteProperty = @"person";
    config.association = @"people";
    config.propertyType = NSRPropertyTypeSendable;
    config.relationshipType = NSRRelationshipTypeHasMany;
    config.nested = YES;
}
```

for every nested property is not client-friendly, prone to errors, and is not very DRY.

I have to ask the question now: _why?_ :)

NSRMap works, its DSL is quite easy to pick up, and compresses a lot of the above code. What functionality does defining each of those delegate methods provide that NSRMap doesn't? If it's just tweaking with property configuration based on runtime state, I would say that that isn't best practice anyway, and to some extent can be done with NSRMap.

And if your irk still lies with the fact that it's a macro, I want to remind you that the macro is super clean - all it does is return a string that NSRails then processes (in the NSRPropertyCollection class, if you're interested.)

I'd also like to mention performance - it may not be _that_ significant, but consider the memory footprint if properties for an entire class have to be allocated on a per-instance, per-request basis.

I hope I'm not being too defensive. I completely understand where you're coming from, but I see no harm in the macro if it does a lot of cleanup on otherwise functionally identical code.

-Dan

PS: I'll give you an alternative if you really aren't a fan. The "NSRPropertyConfiguration" class actually does exist - "NSRProperty" and "NSRPropertyCollection". It is entirely possible to do what you want more or less the way you want to do it. In your subclass's `init`, you can allocate your own instances of NSRProperty, set their attributes however you like them, stick them in a collection, and then assign the collection to the (usually never used) `customProperties` in NSRRemoteObject.

**Comment by dingbat** [comment]
@micpringle I just wanted to let you know - I've been refactoring and rewriting a lot of the NSRRemoteObject source code, and moving NSRMap into overrides like we did for the other macros is making more and more sense.

You can expect to see it deprecated in my next few commits :)

Thanks for your help.

**Comment by ghost** [comment]
**Superb!**

Looking forward to seeing how you approach it :)

**Comment by dingbat** [comment]
I'm glad to say this issue is finally really closed! I made a [cookbook](https://github.com/dingbat/nsrails/wiki/Cookbook) with some examples of the new features, and [here](https://github.com/dingbat/nsrails/wiki/NSRMap) you can see NSRMap's override equivalents.

Let me know if you have any feedback.
