### ISSUE TITLE
How to support offline use? for 50,000+ records

### ISSUE THREAD

**Issue by steve21124** [dingbat/nsrails#15]
If I have 50,000+ records on the server and once downloaded, I want to store it for offline use and sync it if there is newly updated data. Is it possible to use nsrails? like NSRMap?

**Comment by dingbat** [comment]
Of course!

Right now NSRails doesn't natively support pagination (not sure how your backend is serving 50k records... I hope not in one shot), but it's easy enough to set up using the NSRRequest class, and then the `translateRemoteDictionariesIntoInstancesOfClass:` array category method to translate them into objects.

NSRMap is used simply to define how to map the properties of your class with Rails, which you'll probably need to use anyway.

In terms of offline storage, you could simply serialize the array of objects into data, or use CoreData (preferred approach). NSRails was recently upgraded to fully support CoreData-driven apps, so I'd love some feedback if this is the direction you're heading.

**Comment by steve21124** [comment]
Thanks for great info, yes the 50k records will be in one shot. and later if they are changes, user can refresh the records. good tip for "translateRemoteDictionariesIntoInstancesOfClass". 

I am still in researching which technique or plugins  the best method

**Comment by winfred** [comment]
Well while we're on the subject of offline usage...

@dingbat do you have any plans/ideas to bring full offline/sync processes into the NSRails fold? (complex, but perhaps doable)

One such use case: "i'm offline and just created X" where X is placed in a queue for POSTing later. (Side note: it seems this queue would just be all objects with a remoteID of 0)

Or is this beyond the scope that you had in mind? 

It sounds like you're not opposed to the possibility, but I figured it was worth checking in before I start to dive deeper.

Would this feature even be possible/useful without a CoreData dependency? Of course, when using the Rails mentality, you might as well make that decision for the consumer/developer, right?. (Convention > Configuration)

(FWIW, after setting up a handful of models with NSRMap, I think it's a nice DSL.)

**Comment by dingbat** [comment]
I've definitely considered this, but decided at the time it would be best to leave up to the developer. I think there are too many variables for it to be fully integrated (_when should we retry the request? what should happen if it succeeds/fails? what if it's not even relevant anymore?_).

It seems to me that a CoreData dependency would only be required in the specific example that you gave (retrying a create on any objects with 0 remoteID). In my opinion, doing it on a per-request basis would be a much better implementation, since it would extend to any kind of remote action, and not require a persistent store. In other words, store each failed _request_ (now possible with the new NSRRequest class) and resend it sometime later if it fails.

I'm very open to any ideas on implementing this kind of a manager for NSRails, but for me it make most sense right now to leave it up to the developer to store these requests and retry them whenever he/she sees fit.

Actually I'm thinking now - maybe it would be useful to store the NSRRequest object in any returned errors? That way you'd already have the request object, ready to store and retry later.

Let me know if you have any thoughts.

Re: NSRMap - thanks. See issue #14 for the other side of it :)
