### ISSUE TITLE
security&server

### ISSUE THREAD

**Issue by macfree** [dingbat/nsrails#21]
Hey again. First, thanks for an awesome programme. 

How about safety of the server when sending to the server via ip-address:port? 
Is the port open to hackers, port scan and so on? Is it risk of de-coders, meaning making code from executables. Yes im a noob! =)

A friend said not safe, he recommended sending the data to a website which send it to server. 

What are other solutions? The packages to send are not heavy.

**Comment by dingbat** [comment]
Your question seems like a matter of server-side security, for which I'm not an expert exactly!

From my experience: I use HTTP Basic Authentication in my Rails app and it's been working great for 3-4 years now. Never experienced any damage from attacks, and on several occasions I've seen some attempts in the logs. Use a password generator to make both the username and password something tough to brute force.

That being said, I see no reason to do the extra step to your sever. Seems like an overkill to me, will probably open up a ton more work/issues for you, and in the end will only result in more latency from your iOS requests.

So in terms of NSRails, since this is all I've ever needed (never got around to taking a good look at HTTPS), this is all NSRails offers in terms of security. Use NSRConfig's `appUsername` and `appPassword` and NSRails will automatically use those to access your site.

Hope this helped. Look online for adding Basic Auth to your Rails app, there are tons of tutorials.

**Comment by dingbat** [comment]
Can I close this...?

**Comment by macfree** [comment]
OK Thanks!
