### ISSUE TITLE
Unrelated request 

### ISSUE THREAD

**Issue by lukebyrne** [dingbat/nsrails#24]
Hi Dan,

Sorry to stalk you here on an unrelated topic, but I was wondering if you would be able to have a look at this post I made on the Google Groups.

https://groups.google.com/forum/?fromgroups=#!topic/rubymotion/uJyt_v8C2WU

I think with your excellent NSRails project you might be able to assist or shed some light on this issue.

Sorry if posting here is annoyance.

Kind regards,

Luke Byrne

**Comment by dingbat** [comment]
Hey Luke,

No problem, I'd be glad to help. Here's my take on it (and I could be entirely wrong):

It seems to me like the whole login/authentication process is purely browser-based... meaning you need to display only content that the user has access to, and nothing else.

However, in an iOS app, you have complete control over the restrictions of the user. They can't just "type anything into the URL bar." So, the philosophy I've had with my apps is, rather than have the user log in and use that authentication with the server, simply verify the login with Rails but don't rely on this login to restrict content. Instead, I would just have the app request the data that _it_ needs, and have the server grant it. (So just do a GET to that user's ID to retrieve data about it, etc.) Security vulnerability? Perhaps. But if you make your Rails app only accessible via iOS (using basic auth or even SSH), I think it should be okay. Of course I can't say for sure since I don't know your entire situation.

Again, this is just my opinion for a tough question, and I should certainly say that network security (and even Rails) isn't my forte. Definitely consult with others. If you do choose to go with authentication (and need to pass login tokens back and forth), know that NSRails does support this with its "additional HTTP headers."

Anyway, hope this helped to jog some ideas around.
-Dan
