### ISSUE TITLE
Handling of 401 response

### ISSUE THREAD

**Issue by ata-n** [dingbat/nsrails#26]
First off, awesome job on this light and powerful library! thank you.
Second: is there a way to handle http status codes? I know they are being bubbles to the NSError object in every call, but I get different errors (namely an appleError as oppose to a railsError) when my server sends a 401!

heres my log:

2012-11-11 20:01:02.441 ViewDeckExample[50073:c07] [NSRails][OUT] ===> GET to http://localhost:3000/api/v1/me 
2012-11-11 20:01:02.515 ViewDeckExample[50073:c07] [NSRails][connection] Error Domain=NSURLErrorDomain Code=-1012 "The operation couldn’t be completed. (NSURLErrorDomain error -1012.)" UserInfo=0x845f310 {NSErrorFailingURLKey=http://localhost:3000/api/v1/me, NSErrorFailingURLStringKey=http://localhost:3000/api/v1/me, NSUnderlyingError=0x845ebb0 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1012.)"}

I am using Doorkeeper gem on the backend and its issuing the 401 correctly, but here I like to catch it and pop open a login window or something

any thoughts?

Thanks again

**Comment by dingbat** [comment]
Ah yes, a 401 Unauthorized will be caught as an error by NSURLConnection because I think it sees it as a flat-out connection refusal. This is in the same class as, say, a connection issue, a badly formed URL, time out, etc.

I considered for a minute on making an exception for this error code and bubbling it up as a 401 NSRails error, but I think that'd be a bit arbitrary, and we're not even sure it'd always be a 401 (stupidly we can't get the original error code out of Apple's response.)

So, I would just treat it as the NSError that it is. You can make sure the domain is NSURLErrorDomain, and then test the error code for unauthorized (-1012). A list of NSURL error codes can be found [here](http://theshadow.uw.hu/iPhoneSDKdoc/Foundation.framework/NSURLError.h.html). I'd do something like this:

``` objc
error.domain == NSURLErrorDomain &&
 (error.code == NSURLErrorUserAuthenticationRequired ||
  error.code == NSURLErrorUserCancelledAuthentication)
```

**Comment by ata-n** [comment]
haa gotcha! thank you that does it!.

**Comment by dingbat** [comment]
No problemo
