### ISSUE TITLE
Deprecation warnings/errors iOS 6.1 

### ISSUE THREAD

**Issue by fredkelly** [dingbat/nsrails#32]
Hi There,

Love the concept of this library, looks ideal for me (a ruby/rails guy with very little Objective-C experience).

I've just had a go at following your quick screencast on nsrails.com and stumbled into some issues compiling the library:
![Screen Shot 2013-02-15 at 22 27 09](https://f.cloud.github.com/assets/325322/162537/2792469e-77bf-11e2-9f21-b7d08177de6d.png)

Do I need to change some settings to get this to compile, or has the project just not been updated to work with the latest version of iOS?

Many Thanks.

**Comment by dingbat** [comment]
Hi Fred,

I'm embarrassed to say that the screencast at this point won't be of any use, really -- the way the framework is used has fundamentally changed since (but for the better!). I'll make a note of this on the video and hopefully upload a new one if I find the time.

The errors you're getting can be fixed by adding the CoreData framework to your project (required by NSRails even if you're not using CoreData -- but it's something I'd strongly recommend looking into if you're new to iOS). To add it, click on your project file along the left and look in the Build Phases tab, under Link Binary With Libraries.

As per the deprecation warning, thanks for catching that. It should still work for now but I'll commit a change soon that should fix it.

PS: Since the screencast is horribly outdated, I can point you this [section of the readme](https://github.com/dingbat/nsrails#getting-started---objective-c) to get started. Hope it helps.
