### ISSUE TITLE
Using NSRails with RocketPants Rails Back-End

### ISSUE THREAD

**Issue by matthewsinclair** [dingbat/nsrails#35]
I'm using RocketPants on my Rails back-end because it offers some nice features (such as pagination), but I think that because it sends its responses back inside a 'response' entity that it is causing NSRails some problems.

For example with the Stores resource (GET /stores/:id) I end up with:

```
(main)> store = Store.remoteObjectWithID(31, error:e_ptr)
2013-04-05 09:27:51.548 T-Resources[73291:c07] [NSRails][OUT] ===> GET to http://my-service.dev/api/1/stores/31 
2013-04-05 09:27:51.564 T-Resources[73291:c07] [NSRails][IN] <=== Code 200;  {
    response =     {
        "created_at" = "2013-03-31T05:01:04Z";
        currency = AUD;
        id = 31;
        "merchant_id" = 7;
        name = "In molestiae id";
        "updated_at" = "2013-03-31T05:01:04Z";
    };
}
=> #<Store:0xaca0ec0>
(main)> store.currency
=> nil
```

But the returned store object remains unpopulated, which I assume is because the result is inside the "response" entity in the JSON returned. I also noticed that when I tried to get access to a resource that returns a list of items via stores.remoteFetchAll, I'm getting an "unrecognized selector sent to instance" error, presumably because of the RocketPants pagination items (count, pagination) at the end of the response.

Is there anything I can do with NSRails to support a RocketPants-style RESTful API?

Thanks,
M@

**Comment by dingbat** [comment]
> The returned store object remains unpopulated, which I assume is because the result is inside the "response" entity in the JSON returned.

This should be easily fixable (in fact, NSRails already takes into account a wrapper using the model's name, like `store = { ... }`, but it would be good to generalize it to detect any wrapper.)

> I also noticed that when I tried to get access to a resource that returns a list of items via stores.remoteFetchAll, I'm getting an "unrecognized selector sent to instance" error, presumably because of the RocketPants pagination items (count, pagination) at the end of the response.

This is more interesting. What does the response look like on such a call? Is the entire thing being wrapped in "response" again? Or, like you said, is it an array of dictionaries, with a couple extras for count & pagination at the end? An example JSON would be useful.

Thanks!

**Comment by matthewsinclair** [comment]
I'm out at the moment so I don't have access to the returned JSON but from
memory there's two parts:
1. A response block that wraps the underlying raw JSON in response = {...}
2. A pagination block that contains details about any paging that has gone
   on.

I'm using RocketPants which is a pretty popular Rails JSON wrapper.

I think you're probably right that the response wrapper will be easier, but
the second bit might be trickier because it will need to be paging aware.

If I recall correctly, RocketPants provides a client side accessor that
automatically handles pagination. It might be worth checking out how that
works?

Regards,
M@

On 06/04/2013, at 11:09 AM, dan hassin notifications@github.com wrote:

The returned store object remains unpopulated, which I assume is because
the result is inside the "response" entity in the JSON returned.

This should be easily fixable (in fact, NSRails already takes into account
a wrapper using the model's name, like store = { ... }, but it would be
good to generalize it to detect any wrapper.)

I also noticed that when I tried to get access to a resource that returns a
list of items via stores.remoteFetchAll, I'm getting an "unrecognized
selector sent to instance" error, presumably because of the RocketPants
pagination items (count, pagination) at the end of the response.

This is more interesting. What does the response look like on such a call?
Is the entire thing being wrapped in "response" again? Or, like you said,
is it an array of dictionaries, with a couple extras for count & pagination
at the end? An example JSON would be useful.

Thanks!

—
Reply to this email directly or view it on
GitHubhttps://github.com/dingbat/nsrails/issues/35#issuecomment-15987238
.

**Comment by dingbat** [comment]
Ah, I see. I took a look around in RocketPants, the response looks like this:

```
{
  "response": [{
    "id":    1,
    "name": "Delicious Food"
  }, {
    "id":   2,
    "name": "More Delicious Food"
  }],
  "count": 2,
  "pagination": {
    "previous": nil,
    "next":     nil,
    "current":  1,
    "per_page": 10,
    "count":    2,
    "pages":    1
  }
}
```

RIght now NSRails won't support this type of response for a remoteFetchAll, since it's expecting a response of a straight array from the server. I'm assuming your goal is to just call "remoteAll" and get back a list of objects, nicely auto-paginated (repeated calls until nothing left, or at least, a range of items). However, pagination is not supported in NSRails (out of the box). See below.

Pagination has always been on my to-do list for the framework, but I ultimately decided not to implement it straight into NSRails due to the varying different ways that it could be implemented server-side. If only Rails had a built-in paginator, I'd be all for building one around that, but since it does not (to my knowledge... maybe Rails 4 has one?) I'd rather not preference one pagination library over another.

Knowing this, however, I made NSRails as modular as possible so that you could fully implement a paginator that works with your app. NSRails gives you tons of customizability so you can make your request, get the raw JSON response in Ruby objects (arrays, dictionaries), and then do analysis yourself, whether or not to continue to make fetch calls (even with added query parameters in the URL, etc), and amass your data that way. It even makes gritty parts high-level, like transforming a record dictionary from a response into your NSRailsModel object.

It's not too bad to do, and I hope you see the reasoning behind not fully supporting pagination.

**Comment by matthewsinclair** [comment]
I'm happy to craft a custom paginator for my purposes. Where would I start?
What method(s) would I need to override in my model class in order to get
access to the raw response?

On 06/04/2013, at 11:33 AM, dan hassin notifications@github.com wrote:

Ah, I see. I took a look around in RocketPants, the response looks like
this:

{
  "response": [{
    "id":    1,
    "name": "Delicious Food"
  }, {
    "id":   2,
    "name": "More Delicious Food"
  }],
  "count": 2,
  "pagination": {
    "previous": nil,
    "next":     nil,
    "current":  1,
    "per_page": 10,
    "count":    2,
    "pages":    1
  }
}

RIght now NSRails won't support this type of response for a remoteFetchAll,
since it's expecting a response of a straight array from the server. I'm
assuming your goal is to just call "remoteAll" and get back a list of
objects, nicely auto-paginated (repeated calls until nothing left, or at
least, a range of items). However, pagination is not supported in NSRails
(out of the box). See below.

Pagination has always been on my to-do list for the framework, but I
ultimately decided not to implement it straight into NSRails due to the
varying different ways that it could be implemented server-side. If only
Rails had a built-in paginator, I'd be all for building one around that,
but since it does not (to my knowledge... maybe Rails 4 has one?) I'd
rather not preference one pagination library over another.

Knowing this, however, I made NSRails as modular as possible so that you
could fully implement a paginator that works with your app. NSRails gives
you tons of customizability so you can make your request, get the raw JSON
response in Ruby objects (arrays, dictionaries), and then do analysis
yourself, whether or not to continue to make fetch calls (even with added
query parameters in the URL, etc), and amass your data that way. It even
makes gritty parts high-level, like transforming a record dictionary from a
response into your NSRailsModel object.

It's not too bad to do, and I hope you see the reasoning behind not fully
supporting pagination.

—
Reply to this email directly or view it on
GitHubhttps://github.com/dingbat/nsrails/issues/35#issuecomment-15987782
.

**Comment by dingbat** [comment]
No need to override any methods, it's just a matter of calling lower-level methods than "remoteFetchAll".

Have a look at [the documentation](http://dingbat.github.io/nsrails/), it should all be explained clearly.

In particular, you'll want to be looking at [NSRRequest](http://dingbat.github.io/nsrails/Classes/NSRRequest.html). See the examples in the Overview, that'll be what you want to get raw JSON back from your requests.

From there, you can convert a "remote dictionary" (ie, dictionary you got from a server response) into an NSRRemoteObject with `Store.objectWithRemoteDictionary(dict)`, or, if it works better for you, you can put those dictionaries into an array, and then call `array.translateRemoteDictionariesIntoInstancesOfClass(Store)` (yes, Objective-C is verbose) to make those dictionaries into Store objects.

**Comment by dingbat** [comment]
Some other news for the first issue:

After making the fix, I saw that some tests were failing, namely because then response dictionaries for an object that has only a dictionary (and thus, the response dict only contained one item, a dictionary) were being interpreted as a wrapper, rather than as data for that object. A check on an explicit "response" key isn't all that clean either, since there could be data fields with the name "response". While this case might be rare, I'd rather not risk breaking existing apps.

Luckily, though, there's an easy solution to your issue, using overrides in your model. It'd look something like this:

``` ruby
def setPropertiesUsingRemoteDictionary(dict)
    if dict.size == 1 && dict["response"]
        super(dict["response"])
    else
        super(dict)
    end
end
```

Let me know if this works.

**Comment by matthewsinclair** [comment]
Dan,

Thanks for all the feedback. The setPropertiesUsingRemoteDictionary bit worked a treat. It'll take me a few days to get to the pagination stuff. Feel free to close this one out if you like and I'll let you know how i go with the RocketPants binding.

Thanks again,
M@

**Comment by dingbat** [comment]
Sounds good.
