### ISSUE TITLE
NS prefix is bad form for third party libs

### ISSUE THREAD

**Issue by andymoe** [dingbat/nsrails#4]
NS = Next Step and should be left to apple. You should seriously think about changing the prefix for this. Really cool idea though. More discussion.

http://news.ycombinator.com/item?id=4014460

**Comment by winterton** [comment]
Andymoe is correct, NS is reserved by apple to avoid namespace conflicts. You might want to think about using a prefix involving your name or your username. Nice project though.

**Comment by dingbat** [comment]
Thanks, I considered this. The only class that suffers is NSRailsModel - everything else is prefixed with "NSR" (NSRConfig, NSRProperty). I know three-letter prefixes aren't exactly convention, but I believe it should be fine.

NSRailsModel can change though - I took a peek at a fork and was maybe thinking of changing to "NSRManagedObject" or something similar, especially if CoreData gets eventually integrated.

**Comment by ksjogo** [comment]
I think official policy is that You should not use NS\* at all, so no NSR\* as well.

**Comment by dingbat** [comment]
@ksjogo  could you find a source for that?

As far as I can tell from [this guide](https://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingBasics.html#//apple_ref/doc/uid/20001281-1002226), Apple actually does condone three-letter prefixes, meaning that NSR and NS can be considered entirely distinct. Moreover, the guide discourages any "subprefixes", which I'm guessing means that Apple would never even have something like an "R" family of NS.

So with that and the fact that the library compiles fine on a device without conflicts, I see no problem with NSR. If Apple decides to release NSR-prefixed classes that incidentally have to do with Rails, we'll deal with that issue at that time - this risk is the same as with using any other 3rd party framework with its own prefix.

I'm going to leave this open until I rename some things. Feel free to discuss.

**Comment by ksjogo** [comment]
NSR seems like a subprefix to NS which it is definitely not - so it is confusing the devs when writing code for two reasons: It will take longer for autocompletion to kick in, an unknowing coworker might think it is Apple stuff.

I really see no reason why NSR should be choosen instead of something like RR.

**Comment by dingbat** [comment]
I would say name/prefix consistency is more valuable than the extra split second it takes to type the R in NSR.

I don't think anything in NSRails looks like it could be Apple stuff, especially since most of the time methods are called on subclasses, not on NSR classes.

This seems very minor to me, sorry.

**Comment by ksjogo** [comment]
What do you mean with name/prefix consistency?
Nobody else is using NS\* for their custom classes.

**Comment by dingbat** [comment]
Consistency with the name of the library and the prefix of its classes.

This is a dumb argument. Anyone with any Objective-C experience would be able to immediately see the R in NSR. The reason it's called NSRails is because it provides an almost seamless extension to the Foundation NSObject, and the NSR prefix emphasizes that. And at least I didn't use "NSRObject", which may have been cutting it a bit too close :)

Again, I appreciate your input, but these aren't reasons enough to change the prefix. If it bothers you that much you can always find-all + replace.
