### ISSUE TITLE
Make methods to create resources from raw response public

### ISSUE THREAD

**Issue by pareeohnos** [dingbat/nsrails#45]
On one of the screen I'm creating, I'm having to directly interact with `NSRRequest` so I can supply query parameters. I am then calling `sendAsynchronous` which returns a JSON response rather than an array, which is fine, however the method which turns this into an array of resource objects which I'm after, is private

```
+ (NSArray *) arrayOfInstancesFromRemoteJSON:(id)json;
```

Would it not make sense to make this method, (and other methods for fetching) public, so that we could use `NSRRequest` directly, and still easily get resources without having to essentially replicate your code to do so? What I'm hoping to do is something like

```
NSRRequest *request = [NSRRequest requestToFetchAllObjectsOfClass:[User class]];
[request setQueryParameters:@{@"searchString": searchString}];
[request sendAsynchronous:^(id jsonRep, NSError *error) {
    [User arrayOfInstancesFromRemoteJSON:jsonRep];
}];
```

And similar if it is only returning a single result. However, with this method being private I can't do it.

I know I can easily make this public in my local code, just wondered if it would make sense to do this in case others had this issue?

Either that, or let me know if I'm doing something completely wrong!? :)

**Comment by dingbat** [comment]
Haha, there's a public version of it actually – if you take a look at the implementation of `arrayOfInstancesFromRemoteJSON:` – it's tucked away in a category on NSMutableArray. Check out the documentation on it [here](http://dingbat.github.io/nsrails/Categories/NSMutableArray+NSRFetch.html).

You're looking for `translateRemoteDictionariesIntoInstancesOfClass:`, which will convert NSDictionaries in the array into instances of your class:

```
[request sendAsynchronous:^(id jsonRep, NSError *error) {
    [jsonRep translateRemoteDictionariesIntoInstancesOfClass:[User class]];
}];
```

It's typically possible to do anything with this library, just take a good look around the docs :)

**Comment by pareeohnos** [comment]
Ahhh great! Sorry should've dug a little deeper :P

**Comment by dingbat** [comment]
Not a problem man.

**Comment by dingbat** [comment]
(Also I think the longest single-parameter method name in the library...)

**Comment by pareeohnos** [comment]
ha yeah that wouldn't surprise me :P

**Comment by dingbat** [comment]
This issue has actually inspired me to remove the NSMutableArray category entirely. It didn't seem to fit, and turns out to be totally unnecessary, as all the remoteFetchAll methods can be done via the class itself, and, as you were leading on, the "translate..." method fits better there too.

So, from NSRails v2.1 and onwards, the best way to do the above would be something very similar to what you suggested earlier, but using the new

``` objc
+ (NSArray *) objectsWithRemoteDictionaries:(NSArray *)remoteDictionaries;
```

 (note the difference in plurality from `objectWithRemoteDictionary:`).

You'd simply call this on the class for which you want to generate instances, and pass in the JSON you got from the request completion.

I think this simplifies things and is certainly more consistent.

**Comment by pareeohnos** [comment]
Yeah that works perfectly. To me it makes more sense to be in the class itself rather than a category, hence I didn't even think of looking for a category :P
